name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  verify:
    name: run tests before release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv sync --extra test
      - run: uv run coverage run -m pytest -q
      - run: uv run coverage report --fail-under=65

  release:
    runs-on: ubuntu-latest
    needs: [verify]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      - run: uvx twine check dist/*
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
      - name: Publish to PyPI (optional)
        env:
          TWINE_USERNAME: __token__
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ -n "${PYPI_API_TOKEN}" ]; then
            uvx twine upload dist/*
          else
            echo "PYPI_API_TOKEN not set; skipping PyPI publish"
          fi
